# Generated by Django 6.1.1 on 2026-09-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehicle_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='kilometers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='registration_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
