# Generated by Django 6.1.1 on 2026-09-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_vehicle_kilometers_vehicle_registration_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='seller_name',
            field=models.CharField(default='CarCraft Seller', max_length=100),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='seller_phone',
            field=models.CharField(default='9999999999', max_length=15),
        ),
    ]
